import type { AppProps } from "next/app";
import { useEffect, useState } from "react";
import Head from "next/head";
import { evmosTestnet } from "wagmi/chains";
import { publicProvider } from "wagmi/providers/public";
import { configureChains, createClient, WagmiConfig } from "wagmi";
import { Box, ChakraProvider, extendTheme } from "@chakra-ui/react";
import "@styles/globals.css";
import Navbar from "@components/Navbar";
import styles from "@styles/Home.module.css";
import { ConnectKitProvider } from "connectkit";
import { InjectedConnector } from "wagmi/connectors/injected";
import { MetaMaskConnector } from "wagmi/connectors/metaMask";
import { CoinbaseWalletConnector } from "wagmi/connectors/coinbaseWallet";

const { provider } = configureChains([evmosTestnet], [publicProvider()]);

const mm = new MetaMaskConnector({
  chains: [evmosTestnet],
});

const cbw = new CoinbaseWalletConnector({
  chains: [evmosTestnet],
  options: {
    appName: "stakewise",
    jsonRpcUrl: "https://eth.bd.evmos.dev:8545",
  },
});

const injected = new InjectedConnector({
  chains: [evmosTestnet],
});

const wagmiConfig = createClient({
  autoConnect: true,
  connectors: [mm, cbw, injected],
  provider,
});

const theme = extendTheme({
  styles: {
    global: {
      "*": {
        fontFamily: "Plus Jakarta Sans",
        color: "white",
      },
      a: {
        _hover: {
          textDecoration: "none !important",
        },
      },
    },
  },
});

export default function App({ Component, pageProps, router }: AppProps) {
  const [mounted, setMounted] = useState(false);

  useEffect(() => setMounted(true), []);
  if (!mounted) return null;

  return (
    <>
      <WagmiConfig client={wagmiConfig}>
        <ConnectKitProvider theme="midnight">
          <ChakraProvider theme={theme}>
            <Head>
              <title>Demo app</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <Component {...pageProps} key={router.route} />
            <Box className={styles.gradient} />
            <Box className={styles.hero} />
          </ChakraProvider>
        </ConnectKitProvider>
      </WagmiConfig>
    </>
  );
}
